{% set name = "lpsolvers" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lpsolvers-{{ version }}.tar.gz
  sha256: aff363e5e59c48b21a1c1da3ec6d010f2b5f6469bcbf4c8a83bb6f23da31656c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.15.4
    - scipy >=1.2.0

test:
  imports:
    - lpsolvers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Linear programming solvers in Python with a unified API.
  dev_url: https://github.com/stephane-caron/lpsolvers
  license: LGPL-3.0-or-later
  license_file: LICENSE
  home: https://pypi.org/project/lpsolvers

extra:
  recipe-maintainers:
    - stephane-caron
